spring:
    mvc:
          favicon:
             enabled : true
    thymeleaf: 
          cache: false
    datasource:
        url: jdbc:mysql://localhost:3306/aouthdata?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
        username: admin
        password: kukla
    jpa:
        show-sql: false 
        database-platform: org.hibernate.dialect.MySQL5Dialect
        hibernate: 
              ddl-auto: update
              

              